services:
  localstack:
    image: localstack/localstack:3
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
      - DEBUG=0
    volumes:
      - "./.localstack:/var/lib/localstack"

  bff-emprestimo:
    build:
      context: ../bffs/emprestimo
    expose:
      - "4001"
    environment:
      - PORT=4001
      - NODE_ENV=development
      - INTERNAL_GATEWAY_KEY=local-development-gateway-key
    networks:
      - backend

  bff-endereco:
    build:
      context: ../bffs/endereco
    expose:
      - "4002"
    environment:
      - PORT=4002
      - NODE_ENV=development
      - INTERNAL_GATEWAY_KEY=local-development-gateway-key
    networks:
      - backend

  gateway:
    build:
      context: ../gateway
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - NODE_ENV=development
      - CORS_ORIGIN=http://localhost:5173
      - BFF_EMPRESTIMO_URL=http://bff-emprestimo:4001
      - BFF_ENDERECO_URL=http://bff-endereco:4002
      - JWT_SHARED_SECRET=local-development-jwt-secret
      - JWT_ISSUER=portal-dev
      - JWT_AUDIENCE=portal-api
      - INTERNAL_GATEWAY_KEY=local-development-gateway-key
    depends_on:
      - bff-emprestimo
      - bff-endereco
    networks:
      - backend

networks:
  backend:
    internal: true
