services:
  localstack:
    image: localstack/localstack:3
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
      - DEBUG=0
    volumes:
      - "./.localstack:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

  bff-emprestimo:
    build:
      context: ../bffs/emprestimo
    ports:
      - "4001:4001"
    environment:
      - PORT=4001

  bff-endereco:
    build:
      context: ../bffs/endereco
    ports:
      - "4002:4002"
    environment:
      - PORT=4002

  gateway:
    build:
      context: ../gateway
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - CORS_ORIGIN=http://localhost:5173
      - BFF_EMPRESTIMO_URL=http://bff-emprestimo:4001
      - BFF_ENDERECO_URL=http://bff-endereco:4002
    depends_on:
      - bff-emprestimo
      - bff-endereco
